/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SessionPackage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'numberOfSessions' : IDL.Nat,
  'priceCents' : IDL.Nat,
});
export const InquiryStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const BookingInquiry = IDL.Record({
  'status' : InquiryStatus,
  'dogName' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'phone' : IDL.Text,
  'dogBreed' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const InquiryInput = IDL.Record({
  'dogName' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'phone' : IDL.Text,
  'dogBreed' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPackage' : IDL.Func([SessionPackage], [IDL.Nat], []),
  'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
  'deletePackage' : IDL.Func([IDL.Nat], [], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(BookingInquiry)], ['query']),
  'getAllPackages' : IDL.Func([], [IDL.Vec(SessionPackage)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitInquiry' : IDL.Func([InquiryInput], [IDL.Nat], []),
  'updateInquiryStatus' : IDL.Func([IDL.Nat, InquiryStatus], [], []),
  'updatePackage' : IDL.Func([SessionPackage], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SessionPackage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'numberOfSessions' : IDL.Nat,
    'priceCents' : IDL.Nat,
  });
  const InquiryStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const BookingInquiry = IDL.Record({
    'status' : InquiryStatus,
    'dogName' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'phone' : IDL.Text,
    'dogBreed' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const InquiryInput = IDL.Record({
    'dogName' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'phone' : IDL.Text,
    'dogBreed' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPackage' : IDL.Func([SessionPackage], [IDL.Nat], []),
    'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
    'deletePackage' : IDL.Func([IDL.Nat], [], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(BookingInquiry)], ['query']),
    'getAllPackages' : IDL.Func([], [IDL.Vec(SessionPackage)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitInquiry' : IDL.Func([InquiryInput], [IDL.Nat], []),
    'updateInquiryStatus' : IDL.Func([IDL.Nat, InquiryStatus], [], []),
    'updatePackage' : IDL.Func([SessionPackage], [], []),
  });
};

export const init = ({ IDL }) => { return []; };